package com.example.MyBookShopApp.data.book;

import com.example.MyBookShopApp.data.author.AuthorEntity;
import com.example.MyBookShopApp.data.book.file.FileDownloadEntity;
import com.example.MyBookShopApp.data.book.links.Book2AuthorEntity;
import com.example.MyBookShopApp.data.book.links.Book2GenreEntity;
import com.example.MyBookShopApp.data.book.links.Book2UserEntity;
import com.example.MyBookShopApp.data.book.review.BookReviewEntity;
import com.example.MyBookShopApp.data.payments.BalanceTransactionEntity;
import com.example.MyBookShopApp.data.user.UserEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.boot.context.properties.bind.DefaultValue;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "books")
@ApiModel(description = "entity representing a book")
public class BookEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("id generated by db automatically")
    private Long id;
    @Column(name = "pub_date")
    @ApiModelProperty("date of book publication")
    private Date pubDate;
    @ManyToOne
    @JoinColumn(name = "author_id", referencedColumnName = "id")
    @JsonIgnore
    private AuthorEntity author;
    @Column(name = "is_bestseller",columnDefinition = "SMALLINT")
    @ApiModelProperty("if isBestseller = 1 so the book is considered to be bestseller and if 0 the book is not a " +
            "bestseller")
    private Integer isBestseller;
    @Column(columnDefinition = "VARCHAR(225)")
    @ApiModelProperty("mnemonical identity sequence of characters")
    private String slug;
    @Column(columnDefinition = "VARCHAR(225)")
    @ApiModelProperty("book title")
    private String title;
    @Column(columnDefinition = "VARCHAR(225)")
    @ApiModelProperty("book url")
    private String image;
    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("book description text")
    private String description;
    @ApiModelProperty("book price without discount")
    private Integer price;

    @ApiModelProperty("discount value for book")
    private Double discount;

    @Column(name = "relevance")
    @JsonIgnore
    private Double relevance;
//    @ManyToMany
//    @JoinTable( name="book2user",
//            joinColumns= @JoinColumn(name="book_id", referencedColumnName="id"),
//            inverseJoinColumns= @JoinColumn(name="user_id", referencedColumnName="id" ))
//    public List<UserEntity> users;


//    @OneToOne(mappedBy = "bookId")
//    @JsonIgnore
//    private Book2AuthorEntity book2AuthorEntity;
//    @ManyToOne
//    @JsonIgnore
//    private Book2GenreEntity book2GenreEntity;
//    @ManyToOne
//    @JsonIgnore
//    private Book2UserEntity book2UserEntity;
//    @ManyToOne
//    @JsonIgnore
//    private FileDownloadEntity fileDownloadEntity;
//    @ManyToOne
//    @JsonIgnore
//    private BalanceTransactionEntity balanceTransactionEntity;
//    @OneToOne(mappedBy = "bookId")
//    @JsonIgnore
//    private BookReviewEntity bookReviewEntity;



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getPubDate() {
        return pubDate;
    }

    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    public AuthorEntity getAuthor() {
        return author;
    }

    public void setAuthor(AuthorEntity author) {
        this.author = author;
    }

    public Integer getIsBestseller() {
        return isBestseller;
    }

    public void setIsBestseller(Integer isBestseller) {
        this.isBestseller = isBestseller;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public Double getRelevance() {
        return relevance;
    }

    public void setRelevance(Double relevance) {
        this.relevance = relevance;
    }
    //    public Book2AuthorEntity getBook2AuthorEntity() {
//        return book2AuthorEntity;
//    }
//
//    public void setBook2AuthorEntity(Book2AuthorEntity book2AuthorEntity) {
//        this.book2AuthorEntity = book2AuthorEntity;
//    }
//
//    public Book2GenreEntity getBook2GenreEntity() {
//        return book2GenreEntity;
//    }
//
//    public void setBook2GenreEntity(Book2GenreEntity book2GenreEntity) {
//        this.book2GenreEntity = book2GenreEntity;
//    }
//
//    public Book2UserEntity getBook2UserEntity() {
//        return book2UserEntity;
//    }
//
//    public void setBook2UserEntity(Book2UserEntity book2UserEntity) {
//        this.book2UserEntity = book2UserEntity;
//    }
//
//    public FileDownloadEntity getFileDownloadEntity() {
//        return fileDownloadEntity;
//    }
//
//    public void setFileDownloadEntity(FileDownloadEntity fileDownloadEntity) {
//        this.fileDownloadEntity = fileDownloadEntity;
//    }
//
//    public BalanceTransactionEntity getBalanceTransactionEntity() {
//        return balanceTransactionEntity;
//    }
//
//    public void setBalanceTransactionEntity(BalanceTransactionEntity balanceTransactionEntity) {
//        this.balanceTransactionEntity = balanceTransactionEntity;
//    }
//
//    public BookReviewEntity getBookReviewEntity() {
//        return bookReviewEntity;
//    }
//
//    public void setBookReviewEntity(BookReviewEntity bookReviewEntity) {
//        this.bookReviewEntity = bookReviewEntity;
//    }

}
