package com.example.MyBookShopApp.data.author;

import com.example.MyBookShopApp.data.book.BookEntity;
import com.example.MyBookShopApp.data.book.links.Book2AuthorEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db",position = 1)
    private Long id;
    @Column(name = "first_name")
    @ApiModelProperty(value = "first name of author",example = "Bob",position = 2)
    private String firstName;
    @Column(name = "last_name")
    @ApiModelProperty(value = "last name of author", example = "Blaskovits",position = 3)
    private String lastName;
//    @OneToMany(mappedBy = "author")
//    @JsonIgnore
//    private List<BookEntity> bookEntityList = new ArrayList<>();

//    @OneToOne(mappedBy = "authorId")
//    @JsonIgnore
//    private Book2AuthorEntity book2AuthorEntity;


//    public List<BookEntity> getBookEntityList() {
//        return bookEntityList;
//    }
//
//    public void setBookEntityList(List<BookEntity> bookEntityList) {
//        this.bookEntityList = bookEntityList;
//    }

//    public Book2AuthorEntity getBook2AuthorEntity() {
//        return book2AuthorEntity;
//    }
//
//    public void setBook2AuthorEntity(Book2AuthorEntity book2AuthorEntity) {
//        this.book2AuthorEntity = book2AuthorEntity;
//    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String first_name) {
        this.firstName = first_name;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String last_name) {
        this.lastName = last_name;
    }
}
