package com.example.MyBookShopApp.data.author;

import com.example.MyBookShopApp.data.book.BookEntity;
import com.example.MyBookShopApp.data.book.links.Book2AuthorEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db",position = 1)
    private Long id;
    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty(value = "author's photo",example = "http://dummyimage.com/600x949.png/ff4444/ffffff",position = 2)
    private String photo;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "unique code of author",example = "author-asd-123",position = 3)
    private String slug;

    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    @ApiModelProperty(value = "full name of author",example = "Bob Blaskovits",position = 4)
    private String name;

    @Column(columnDefinition = "TEXT")
    @ApiModelProperty(value = "description of author",example = "neque libero convallis eget eleifend luctus " +
            "ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante",position = 5)
    private String description;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
